# Generated by Django 5.1 on 2024-09-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_remove_audio_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='type_audio',
            field=models.CharField(choices=[('english', 'English'), ('turkmen', 'Turkmen'), ('russian', 'Russian'), ('traditional', 'Traditional'), ('tale', 'Tales'), ('huwdi', 'Huwdi')], default='turkmen', max_length=100),
        ),
    ]
