# Generated by Django 5.1 on 2024-10-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_audio_type_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='lang_audio',
            field=models.CharField(choices=[('english', 'English'), ('turkmen', 'Turkmen'), ('russian', 'Russian')], default='turkmen', max_length=100),
        ),
        migrations.AlterField(
            model_name='audio',
            name='type_audio',
            field=models.CharField(choices=[('erteki', 'Erteki'), ('gosgy', 'Gosgy'), ('aydym', 'Aydym'), ('halk', 'Halk Doredijiligi')], default='aydym', max_length=100),
        ),
    ]
