# Generated by Django 5.1 on 2024-10-13 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audio_lang_audio_alter_audio_type_audio'),
        ('channel', '0008_categorykids_categoryparents_categoryteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_category', to='channel.categorykids'),
        ),
    ]
