# Generated by Django 5.1 on 2024-09-27 09:18

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogforteachers',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='blogforteachers',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='blogforteachers',
            name='description_tm',
        ),
        migrations.AddField(
            model_name='blogforteachers',
            name='title_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogforteachers',
            name='title_ru',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogforteachers',
            name='title_tm',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogforteachers',
            name='thumbnail',
            field=models.ImageField(upload_to='images/parents/', validators=[teachers.models.validate_img_file_extension]),
        ),
    ]
