# Generated by Django 5.1 on 2024-09-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('channel', '0004_alter_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='channel.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='channel',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_channel', to='channel.channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='lesson',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_lesson', to='channel.lesson'),
            preserve_default=False,
        ),
    ]
