# Generated by Django 5.1 on 2024-09-16 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_category_book_channel_book_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unique_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
