# Generated by Django 5.1 on 2024-09-27 09:00

import ckeditor.fields
import ui.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDailyBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('title_tm', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('content_tm', ckeditor.fields.RichTextField(null=True)),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('thumbnail', models.ImageField(upload_to='images/ui/', validators=[ui.models.validate_img_file_extension])),
                ('is_active', models.BooleanField(default=False)),
                ('is_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
