# Generated by Django 5.1 on 2024-09-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedailyblog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='homedailyblog',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='homedailyblog',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='homedailyblog',
            name='title_tm',
        ),
    ]
