# Generated by Django 5.1 on 2024-10-13 08:57

import ui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_remove_homedailyblog_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAudioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_audio', models.CharField(choices=[('hemmesi', 'Hemmesi'), ('erteki', 'Erteki'), ('gosgy', 'Gosgy'), ('aydym', 'Aydym'), ('halk', 'Halk Doredijiligi')], default='aydym', max_length=100)),
                ('thumbnail', models.ImageField(upload_to='images/ui/', validators=[ui.models.validate_img_file_extension])),
                ('order_no', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
