# Generated by Django 5.1 on 2024-10-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_homeaudioimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeaudioimages',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeaudioimages',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeaudioimages',
            name='name_tm',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
