# Generated by Django 5.1 on 2024-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
