# Generated by Django 5.1 on 2024-10-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type_category',
            field=models.CharField(choices=[('kids', 'Korpeler'), ('parents', 'Ene Atalar'), ('teachers', 'Terbiyeciler')], default='kids', max_length=100),
        ),
    ]
