# Generated by Django 5.1 on 2024-10-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_alter_audio_category'),
        ('blog', '0002_alter_blog_category'),
        ('book', '0006_alter_book_category'),
        ('channel', '0008_categorykids_categoryparents_categoryteachers'),
        ('parents', '0002_alter_blogforparents_category'),
        ('teachers', '0003_alter_blogforteachers_category_and_more'),
        ('video', '0005_alter_video_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
