# Generated by Django 5.1 on 2024-10-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorykids',
            name='category_type',
            field=models.CharField(choices=[('video', 'Videolar'), ('book', 'Kitaplar'), ('blog', 'Bloglar')], default='video', max_length=100),
        ),
    ]
