# Generated by Django 5.1 on 2024-10-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0010_categorykids_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorykids',
            name='name_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categorykids',
            name='name_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categorykids',
            name='name_tm',
            field=models.CharField(max_length=255),
        ),
    ]
