# Generated by Django 5.1 on 2024-10-13 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_categorykids_categoryparents_categoryteachers'),
        ('video', '0004_videoview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_category', to='channel.categorykids'),
        ),
    ]
